# Generated by Django 3.2.7 on 2022-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading0', models.CharField(default='', max_length=500)),
                ('content_heading0', models.CharField(default='', max_length=5000)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('content_heading1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=500)),
                ('content_heading2', models.CharField(default='', max_length=5000)),
                ('publish_date', models.DateField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
