# Generated by Django 4.0.2 on 2022-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blogs/uploads'),
            preserve_default=False,
        ),
    ]
