# Generated by Django 4.0.2 on 2022-02-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='thumbnail',
        ),
    ]
